import Link from 'next/Link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import utilstyles from '../styles/utils.module.css'
import { getPostData } from '../lib/post'

export async function getStaticProps() {
  const allPostsData = getPostData();
  console.log(allPostsData);

  return {
    props: {
      allPostsData,
    }
  }
}

export default function Home({ allPostsData }) {
  return (
    <div className={styles.container}>

      <Head>
        <title>Next.js blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section>
          <p className={utilstyles.headingMd}>
            Nextjs学習用
          </p>
        </section>

        <section>
          <div className={styles.grid}>
            <article>
              <Link href='/'>
                <img src='/imgs/thumbnail01.jpg' className={styles.thumbnailImage}></img>
                <a className={utilstyles.boldText}>
                  SSGとSSRの使い分けの場面はいつなのか？
                </a>
                <br></br>
              </Link>
              <small className={utilstyles.lightText}>
                22/11/06
              </small>
            </article>
            <article>
              <Link href='/'>
                <img src='/imgs/thumbnail02.jpg' className={styles.thumbnailImage}></img>
                <a className={utilstyles.boldText}>
                  SSGとSSRの使い分けの場面はいつなのか？
                </a>
                <br></br>
              </Link>
              <small className={utilstyles.lightText}>
                22/11/06
              </small>
            </article>
            <article>
              <Link href='/'>
                <img src='/imgs/thumbnail03.jpeg' className={styles.thumbnailImage}></img>
                <a className={utilstyles.boldText}>
                  SSGとSSRの使い分けの場面はいつなのか？
                </a>
                <br></br>
              </Link>
              <small className={utilstyles.lightText}>
                22/11/06
              </small>
            </article>
            <article>
              <Link href='/'>
                <img src='/imgs/thumbnail04.jpg' className={styles.thumbnailImage}></img>
                <a className={utilstyles.boldText}>
                  SSGとSSRの使い分けの場面はいつなのか？
                </a>
                <br></br>
              </Link>
              <small className={utilstyles.lightText}>
                22/11/06
              </small>
            </article>
          </div>
        </section>

      </Layout>

    </div>
  )
}
