import Link from 'next/Link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import utilstyles from '../styles/utils.module.css'
import { getPostData } from '../lib/post'

export async function getStaticProps() {
  const allPostsData = getPostData();
  console.log(allPostsData);

  return {
    props: {
      allPostsData,
    }
  }
}

export default function Home({ allPostsData }) {
  return (
    <div className={styles.container}>

      <Head>
        <title>Next.js blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section>
          <p className={utilstyles.headingMd}>
            Nextjs学習用
          </p>
        </section>

        <section>
          <div className={styles.grid}>
            {allPostsData.map(({ id, title, date, thumbnail }) => (
             <article key = {id}>
              <Link href={`/posts/${id}`}>
                <img src={`${thumbnail}`} className={styles.thumbnailImage}></img>
              </Link>
                <a className={utilstyles.boldText}>{title}</a>
              <br />
              <small className={utilstyles.lightText}>
                {date}
              </small>
            </article>
            ))}
          </div>
        </section>
      </Layout>

    </div>
  )
}
